//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeaKona.AutoInterfaceGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutoInterfaceResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutoInterfaceResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeaKona.AutoInterfaceGenerator.AutoInterfaceResource", typeof(AutoInterfaceResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG01_description {
            get {
                return ResourceManager.GetString("AG01_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not marked as partial..
        /// </summary>
        internal static string AG01_message {
            get {
                return ResourceManager.GetString("AG01_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not marked as partial..
        /// </summary>
        internal static string AG01_title {
            get {
                return ResourceManager.GetString("AG01_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG02_description {
            get {
                return ResourceManager.GetString("AG02_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is static..
        /// </summary>
        internal static string AG02_message {
            get {
                return ResourceManager.GetString("AG02_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is static..
        /// </summary>
        internal static string AG02_title {
            get {
                return ResourceManager.GetString("AG02_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG03_description {
            get {
                return ResourceManager.GetString("AG03_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not an interface..
        /// </summary>
        internal static string AG03_message {
            get {
                return ResourceManager.GetString("AG03_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not an interface..
        /// </summary>
        internal static string AG03_title {
            get {
                return ResourceManager.GetString("AG03_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG04_description {
            get {
                return ResourceManager.GetString("AG04_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast from type &apos;{0}&apos; to &apos;{1}&apos; or type &apos;{0}&apos; does not expose all members required by interface &apos;{1}&apos;..
        /// </summary>
        internal static string AG04_message {
            get {
                return ResourceManager.GetString("AG04_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to cast or missing member..
        /// </summary>
        internal static string AG04_title {
            get {
                return ResourceManager.GetString("AG04_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG05_description {
            get {
                return ResourceManager.GetString("AG05_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not implement interface &apos;{0}&apos;..
        /// </summary>
        internal static string AG05_message {
            get {
                return ResourceManager.GetString("AG05_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type does not implement a defined interface(s)..
        /// </summary>
        internal static string AG05_title {
            get {
                return ResourceManager.GetString("AG05_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG06_description {
            get {
                return ResourceManager.GetString("AG06_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; does not have getter..
        /// </summary>
        internal static string AG06_message {
            get {
                return ResourceManager.GetString("AG06_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target member is writeonly..
        /// </summary>
        internal static string AG06_title {
            get {
                return ResourceManager.GetString("AG06_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG07_description {
            get {
                return ResourceManager.GetString("AG07_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be null..
        /// </summary>
        internal static string AG07_message {
            get {
                return ResourceManager.GetString("AG07_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type should be an interface..
        /// </summary>
        internal static string AG07_title {
            get {
                return ResourceManager.GetString("AG07_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG08_description {
            get {
                return ResourceManager.GetString("AG08_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only class, record or struct can auto-implement interface..
        /// </summary>
        internal static string AG08_message {
            get {
                return ResourceManager.GetString("AG08_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not a class, record, or struct..
        /// </summary>
        internal static string AG08_title {
            get {
                return ResourceManager.GetString("AG08_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG09_description {
            get {
                return ResourceManager.GetString("AG09_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal exception [{0}]..
        /// </summary>
        internal static string AG09_message {
            get {
                return ResourceManager.GetString("AG09_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal exception..
        /// </summary>
        internal static string AG09_title {
            get {
                return ResourceManager.GetString("AG09_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG10_description {
            get {
                return ResourceManager.GetString("AG10_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoInterface template for single interface should be defined at most once..
        /// </summary>
        internal static string AG10_message {
            get {
                return ResourceManager.GetString("AG10_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple AutoInterface templates..
        /// </summary>
        internal static string AG10_title {
            get {
                return ResourceManager.GetString("AG10_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG11_description {
            get {
                return ResourceManager.GetString("AG11_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file &apos;{0}&apos; not found..
        /// </summary>
        internal static string AG11_message {
            get {
                return ResourceManager.GetString("AG11_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file not found..
        /// </summary>
        internal static string AG11_title {
            get {
                return ResourceManager.GetString("AG11_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG12_description {
            get {
                return ResourceManager.GetString("AG12_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template should be specified either inline or from file but not both..
        /// </summary>
        internal static string AG12_message {
            get {
                return ResourceManager.GetString("AG12_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one template specified..
        /// </summary>
        internal static string AG12_title {
            get {
                return ResourceManager.GetString("AG12_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG13_description {
            get {
                return ResourceManager.GetString("AG13_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify both AutoInterface.Template and AutoInterfaceTemplate simultaneously..
        /// </summary>
        internal static string AG13_message {
            get {
                return ResourceManager.GetString("AG13_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify both AutoInterface.Template and AutoInterfaceTemplate simultaneously..
        /// </summary>
        internal static string AG13_title {
            get {
                return ResourceManager.GetString("AG13_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG14_description {
            get {
                return ResourceManager.GetString("AG14_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template is missing..
        /// </summary>
        internal static string AG14_message {
            get {
                return ResourceManager.GetString("AG14_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template is missing..
        /// </summary>
        internal static string AG14_title {
            get {
                return ResourceManager.GetString("AG14_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG15_description {
            get {
                return ResourceManager.GetString("AG15_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter &apos;{0}&apos; is not valid Regex expression..
        /// </summary>
        internal static string AG15_message {
            get {
                return ResourceManager.GetString("AG15_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter is not valid Regex expression..
        /// </summary>
        internal static string AG15_title {
            get {
                return ResourceManager.GetString("AG15_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AG16_description {
            get {
                return ResourceManager.GetString("AG16_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple partial templates found for member: &apos;{0}&apos;..
        /// </summary>
        internal static string AG16_message {
            get {
                return ResourceManager.GetString("AG16_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple partial templates found..
        /// </summary>
        internal static string AG16_title {
            get {
                return ResourceManager.GetString("AG16_title", resourceCulture);
            }
        }
    }
}
